gText_Birch_Welcome::
	.string "... ... ...\p"
	.string "Am I dreaming?.\p"
	.string "Who am I?$"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Who am I?!$"

gText_Birch_BoyOrGirl::
	.string "Am I a boy?\n"
	.string "Or am I a girl?$"

gText_Birch_WhatsYourName::
	.string "That adds up, I think.\n"
	.string "What's my name?$"

gText_Birch_SoItsPlayer::
	.string "Is it really {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, right!\p"
	.string "I don't know how I forgot.\n"
	.string "I'm visiting my friend in the Vulias region.\l"
	.string "in the Vulias region.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Ah, right!\n"
	.string "I don't know how I forgot.\l"
	.string "Now I remember what's going on!\p"
	.string "I'm visiting my friend in the Vulias region.\n"
	.string "He moved here from the Alola region a\l"
	.string "few years ago, where we both grew up. I\l"
	.string "decided to visit, and see the region\l"
	.string "for myself!\p"
	.string "I want to travel around the region to\n"
	.string "explore all the sights! Who knows what\l"
	.string "could unfold? Maybe this place will\l"
	.string "become special to me!\p"
	.string "I have a Pokémon who is my best friend,\n"
	.string "they are very important to me.\l"
	.string "What is that Pokemon...\p"
	.string "$"
