gText_Birch_Welcome::
	.string "Looks like you are having a dream.\p"
	.string "Who am I?!$"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Who am I?!$"

gText_Birch_BoyOrGirl::
	.string "Am I a boy?\n"
	.string "Or am I a girl?$"

gText_Birch_WhatsYourName::
	.string "That adds up.\n"
	.string "What's my name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, right!\p"
	.string "I don't know how I forgot.\n"
	.string "I'm visiting my friend\l"
	.string "in the XXX region.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "I want to travel around the region?\p"
	.string "to explore all the sights! Who knows\n"
	.string "what could unfold?\p"
	.string "I had a Pokémon who is my best\n"
	.string "friend, who was that...\p"
	.string "$"
