Vulias_FlorensythSea_MapScripts::
	.byte 0


FlorensythSea_EventScript_GerbonTownSign::
# 5 "data/maps/Vulias_FlorensythSea/scripts.pory"
	lockall
# 6 "data/maps/Vulias_FlorensythSea/scripts.pory"
	msgbox FlorensythSea_EventScript_GerbonTownSign_Text_0
# 8 "data/maps/Vulias_FlorensythSea/scripts.pory"
	releaseall
	return


FlorensythSea_EventScript_GerbonTownSign_Text_0:
# 6 "data/maps/Vulias_FlorensythSea/scripts.pory"
	.string "{RIGHT_ARROW} Florensyth Sea\n"
	.string "{LEFT_ARROW} Gerbon Town$"
