voice_group gm_banjo_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_110d78c, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110d78c, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110db9c, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110db9c, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110db9c, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110df98, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110df98, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1037728, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1046914, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1046914, 255, 254, 0, 235
