voice_group gm_bass_and_lead_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_10f5f60, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10f5f60, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10f6ca8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10f6ca8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10f6ca8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10f6ca8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10f76e0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10f76e0, 255, 0, 255, 235
