voice_group gm_blown_bottle_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_10d250c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d250c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d250c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d2d08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c5638, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c5638, 255, 0, 255, 235
