voice_group gm_brass_section_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_10b1f08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b1f08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b1f08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b1f08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b3c38, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b5c48, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b5c48, 255, 0, 255, 235
