voice_group gm_chiffer_lead_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_10ed380, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ee964, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ee964, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ee964, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ee964, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ee964, 255, 0, 255, 235
