voice_group gm_drawbar_organ_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_10403e8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10403e8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10403e8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10403e8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10403e8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_104061c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_104061c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1040744, 255, 0, 255, 235
