voice_group gm_electric_piano_1_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_1031628, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_10319fc, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_10319fc, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_10319fc, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1031d54, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1031d54, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1031f08, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1031f08, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1031f08, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1032108, 255, 254, 0, 235
