voice_group gm_electric_bass_finger_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_1070a90, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_10715a8, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_1071fbc, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_1071fbc, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_1071fbc, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_1071fbc, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_1071fbc, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_1071fbc, 255, 242, 103, 235
