voice_group gm_french_horn_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_10af85c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b0f00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b0f00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b0f00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b0f00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b0f00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_108ab84, 255, 0, 255, 235
