voice_group gm_fantasia_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_10f8030, 255, 0, 255, 238
	voice_directsound 60, 0, DirectSoundWaveData_10f8030, 255, 0, 255, 238
	voice_directsound 60, 0, DirectSoundWaveData_10f8030, 255, 0, 255, 238
	voice_directsound 60, 0, DirectSoundWaveData_10f959c, 255, 0, 255, 238
	voice_directsound 60, 0, DirectSoundWaveData_10f959c, 255, 0, 255, 238
	voice_directsound 60, 0, DirectSoundWaveData_10f959c, 255, 0, 255, 238
	voice_directsound 60, 0, DirectSoundWaveData_1038ee8, 255, 0, 255, 238
