voice_group gm_ice_rain_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_1102900, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1102900, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_10f5014, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_10f5014, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_10f5014, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_10f5014, 255, 254, 0, 235
