voice_group gm_kalimba_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_110fb98, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110fb98, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110fb98, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110fb98, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110fb98, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_10701f8, 255, 242, 0, 235
