voice_group gm_music_box_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_1039410, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1039410, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1038e48, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1038e48, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1038e48, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1038ee8, 255, 249, 0, 235
