voice_group gm_marimba_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_103e954, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_103f0dc, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_103f0dc, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_103f0dc, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1038ee8, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1038ee8, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1038ee8, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1038ee8, 255, 249, 0, 235
