voice_group gm_pizzicato_strings_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_1094628, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1094628, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1094628, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1094628, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1094fe0, 255, 242, 0, 235
