voice_group gm_pan_flute_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_10d15f4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d15f4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d15f4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d15f4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c5638, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c5638, 255, 0, 255, 235
