voice_group gm_piccolo_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_10cd288, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd748, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd748, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd748, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd748, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cda0c, 255, 0, 255, 235
