voice_group gm_slap_bass_1_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_107af1c, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_107cc28, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_107cc28, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_107cc28, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_107e1a8, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_107e1a8, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_107e1a8, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_1054bfc, 255, 252, 51, 235
