voice_group gm_synthbrass_2_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_10bdaf4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c002c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c002c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c16b8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c16b8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c16b8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a3f94, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a3f94, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a3f94, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a3f94, 255, 0, 255, 235
