voice_group gm_sweep_pad_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_1096f48, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1099a38, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1099a38, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109c55c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109c55c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109c55c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109c55c, 255, 0, 255, 235
