voice_group gm_synth_voice_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_10a4924, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a4924, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a4924, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a5e38, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a5e38, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1048424, 255, 0, 255, 235
