voice_group gm_synth_bass_2_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_10849bc, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_108707c, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_108707c, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_1087cb4, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_1087cb4, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_1087cb4, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_1087cb4, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_1087cb4, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_1054bfc, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_1054bfc, 255, 254, 51, 235
