voice_group gm_string_ensemble_1_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_108d4f4, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_108fbf0, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109289c, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109289c, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109289c, 128, 0, 255, 235
