voice_group gm_sitar_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_110d1e0, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_110d41c, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_110d41c, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_110d60c, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_10480d0, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_10480d0, 255, 254, 25, 235
