voice_group gm_synthstrings_2_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_1096f48, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1099a38, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1099a38, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109c55c, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109c55c, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109c55c, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109c55c, 128, 0, 255, 235
