voice_group gm_tremolo_strings_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_108d4f4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_108fbf0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109289c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109289c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109289c, 255, 0, 255, 235
