voice_group gm_vibraphone_keysplit
	voice_directsound 60, 0, DirectSoundWaveData_1039740, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1039740, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1039740, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1039740, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_103b0e4, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_103b0e4, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_103b0e4, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_103c84c, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_103c84c, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_103d62c, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_103d62c, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_103d62c, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_103df8c, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_103df8c, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_103df8c, 255, 254, 0, 235
