ZED_SawgrassForest_MapScripts::
	.byte 0


SawgrassForest_EventScript_WarningSign::
# 5 "data/maps/ZED_SawgrassForest/scripts.pory"
	lock
# 6 "data/maps/ZED_SawgrassForest/scripts.pory"
	msgbox SawgrassForest_EventScript_WarningSign_Text_0
	return


SawgrassForest_EventScript_WarningSign_Text_0:
# 6 "data/maps/ZED_SawgrassForest/scripts.pory"
	.string "WARNING:\p"
	.string "Patrols in Sawgrass Forest are not\n"
	.string "frequent.\p"
	.string "Stick to the lamplight for safety.$"
